# rooialty_ai_rag/output/formatter.py
# Serialises the full architecture analysis into:
#   claude_context.json      — structured map for Claude
#   claude_context_summary.txt — human-readable plain text

import json
from datetime import datetime, timezone
from pathlib import Path

OUTPUT_DIR = Path(__file__).parent


def format_context(
    all_files,
    supabase_files,
    db_descriptions,
    schema,
    known_tables,
    graph,
    architecture,
):
    doc = _build_document(
        all_files, supabase_files, db_descriptions,
        schema, known_tables, graph, architecture,
    )

    json_path = OUTPUT_DIR / "claude_context.json"
    txt_path  = OUTPUT_DIR / "claude_context_summary.txt"

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)

    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(_build_summary(doc))

    return json_path, txt_path


# ─────────────────────────────────────────────────────────────────
# JSON document
# ─────────────────────────────────────────────────────────────────

def _build_document(
    all_files, supabase_files, db_descriptions,
    schema, known_tables, graph, arch,
):
    stats = graph["stats"]

    return {
        # ── Meta ──────────────────────────────────────────────────
        "_meta": {
            "generated_at":          datetime.now(timezone.utc).isoformat(),
            "pipeline":              "rooialty_ai_rag",
            "purpose":               "Full system architecture map — frontend ↔ DB",
            "total_frontend_files":  len(all_files),
            "supabase_files":        len(supabase_files),
            "db_tables_known":       len(known_tables),
            "db_tables_covered":     stats["total_tables_referenced"],
        },

        # ── Instructions for Claude ───────────────────────────────
        "claude_instructions": (
            "You are a full-stack assistant with expert knowledge of the "
            "Rooialty restaurant management application.\n\n"
            "This document was auto-generated by an RAG pipeline that:\n"
            "  1. Scanned every .js/.jsx file in src/ for Supabase calls\n"
            "  2. Mapped those calls to PostgreSQL tables\n"
            "  3. Built a complete frontend ↔ DB relationship graph\n"
            "  4. Classified files by role (hook / page / component)\n"
            "  5. Identified gaps, orphans, read-only tables, and "
                 "direct writes bypassing the hook layer\n\n"
            "Use this to:\n"
            "  • Trace any feature end-to-end from UI → hook → DB table\n"
            "  • Identify missing queries, broken joins, or wrong filters\n"
            "  • Understand which tables are read-only, write-heavy, "
                 "or completely unconnected\n"
            "  • Reason about the full data model and how it maps to the UI\n"
            "  • Suggest minimal, targeted fixes grounded in actual "
                 "code structure"
        ),

        # ── Scan summary ──────────────────────────────────────────
        "scan_summary": {
            "total_files_scanned":    len(all_files),
            "files_using_supabase":   len(supabase_files),
            "db_tables_known":        len(known_tables),
            "db_tables_referenced":   stats["total_tables_referenced"],
            "db_tables_unreferenced": graph["orphan_tables"],
        },

        # ── File role classification ──────────────────────────────
        "file_roles": {
            "description": (
                "Frontend files classified by role. "
                "Hooks are the preferred data layer — pages should go "
                "through hooks rather than querying Supabase directly. "
                "See gap_analysis.direct_writes_bypassing_hooks for violations."
            ),
            "hooks":      arch["hooks"],
            "pages":      arch["pages"],
            "components": arch["components"],
            "utilities":  arch["utilities"],
        },

        # ── Frontend → DB map ─────────────────────────────────────
        "frontend_to_db_map": graph["file_to_tables"],

        # ── DB → Frontend map ─────────────────────────────────────
        "db_to_frontend_map": graph["table_to_files"],

        # ── Per-table deep profile ────────────────────────────────
        "table_profiles": _build_table_profiles(
            known_tables, arch["table_ops"],
            arch["filtered_columns"], db_descriptions,
        ),

        # ── Gap analysis ──────────────────────────────────────────
        "gap_analysis": {
            "orphan_db_tables": {
                "description": (
                    "DB tables that exist but are NEVER queried from the "
                    "frontend. May be backend-only, missing features, "
                    "or legacy."
                ),
                "tables": graph["orphan_tables"],
            },
            "orphan_frontend_files": {
                "description": (
                    "Frontend files that use Supabase but reference no "
                    "known DB table. May use dynamic table names or "
                    "auth-only calls."
                ),
                "files": graph["orphan_files"],
            },
            "read_only_tables": {
                "description": (
                    "Tables only ever SELECTed from the frontend — never "
                    "inserted, updated, or deleted. May be intentional "
                    "(views, reference data) or a missing feature."
                ),
                "tables": arch["read_only_tables"],
            },
            "direct_writes_bypassing_hooks": {
                "description": (
                    "Page or component files that write directly to "
                    "Supabase instead of going through a hook. Can lead "
                    "to duplicated logic and harder-to-trace bugs."
                ),
                "entries": arch["direct_write_files"],
            },
        },

        # ── Enum catalogue ────────────────────────────────────────
        "enum_catalogue": {
            "description": (
                "All PostgreSQL enums. Frontend code must use exactly "
                "these string values when filtering or inserting."
            ),
            "enums": arch["enum_types"],
        },

        # ── Filtered columns by table ─────────────────────────────
        "filtered_columns_by_table": arch["filtered_columns"],

        # ── Raw table descriptions from rooialty_ai ───────────────
        "db_table_descriptions": db_descriptions,

        # ── Schema artefacts ──────────────────────────────────────
        "schema_artefacts": {
            k: v for k, v in schema.items()
            if k in ("constraints", "enums", "table+column")
        },

        # ── All Supabase files (flat list) ────────────────────────
        "all_supabase_files": [
            {
                "file":       _rel(f.get("file", "")),
                "role":       f.get("role", "unknown"),
                "tables":     f.get("tables", []),
                "operations": f.get("operations", []),
                "realtime":   f.get("realtime", False),
            }
            for f in supabase_files
        ],
    }


# ─────────────────────────────────────────────────────────────────
# Plain-text summary
# ─────────────────────────────────────────────────────────────────

def _build_summary(doc):
    lines = []
    w = lines.append

    w("=" * 70)
    w("ROOIALTY — FULL SYSTEM ARCHITECTURE SUMMARY")
    w(f"Generated: {doc['_meta']['generated_at']}")
    w("=" * 70)

    m = doc["_meta"]
    w(f"\nFrontend files scanned : {m['total_frontend_files']}")
    w(f"Files using Supabase   : {m['supabase_files']}")
    w(f"DB tables known        : {m['db_tables_known']}")
    w(f"DB tables with coverage: {m['db_tables_covered']}")

    # ── Table profiles ────────────────────────────────────────────
    w("\n" + "─" * 70)
    w("TABLE PROFILES")
    w("─" * 70)
    for table, profile in doc["table_profiles"].items():
        ops      = ", ".join(profile["operations"]) or "none"
        rt       = "  [realtime]" if profile["realtime"] else ""
        filtered = ", ".join(profile["filtered_columns"]) or "—"
        w(f"\n  {table.upper()}{rt}")
        w(f"    Operations : {ops}")
        w(f"    Readers    : {len(profile['readers'])} file(s)")
        w(f"    Writers    : {len(profile['writers'])} file(s)")
        w(f"    Filtered on: {filtered}")
        for r in profile["readers"]:
            w(f"      read  ← {_rel(r)}")
        for wr in profile["writers"]:
            w(f"      write → {_rel(wr)}")

    # ── Hooks ─────────────────────────────────────────────────────
    w("\n" + "─" * 70)
    w("HOOKS  (data layer)")
    w("─" * 70)
    for fname, info in doc["file_roles"]["hooks"].items():
        w(f"  {fname}")
        w(f"    tables: {', '.join(info['tables']) or '—'}  |  "
          f"ops: {', '.join(info['operations']) or '—'}"
          f"{'  [realtime]' if info['realtime'] else ''}")

    # ── Pages ─────────────────────────────────────────────────────
    w("\n" + "─" * 70)
    w("PAGES")
    w("─" * 70)
    for fname, info in doc["file_roles"]["pages"].items():
        w(f"  {fname}")
        w(f"    tables: {', '.join(info['tables']) or '—'}  |  "
          f"ops: {', '.join(info['operations']) or '—'}")

    # ── Components ────────────────────────────────────────────────
    w("\n" + "─" * 70)
    w("COMPONENTS")
    w("─" * 70)
    for fname, info in doc["file_roles"]["components"].items():
        w(f"  {fname}")
        w(f"    tables: {', '.join(info['tables']) or '—'}  |  "
          f"ops: {', '.join(info['operations']) or '—'}")

    # ── Gap analysis ──────────────────────────────────────────────
    w("\n" + "─" * 70)
    w("GAP ANALYSIS")
    w("─" * 70)
    ga = doc["gap_analysis"]

    orphan_db = ga["orphan_db_tables"]["tables"]
    w(f"\n  Uncovered DB tables ({len(orphan_db)}):")
    for t in orphan_db:
        w(f"    ⚠  {t}")

    orphan_fe = ga["orphan_frontend_files"]["files"]
    w(f"\n  Orphan frontend files ({len(orphan_fe)}):")
    for f in orphan_fe:
        w(f"    ⚠  {_rel(f)}")

    ro = ga["read_only_tables"]["tables"]
    w(f"\n  Read-only tables ({len(ro)}):")
    for t in ro:
        w(f"    ℹ  {t}")

    dw = ga["direct_writes_bypassing_hooks"]["entries"]
    w(f"\n  Direct writes bypassing hooks ({len(dw)}):")
    for e in dw:
        w(f"    ⚠  {_rel(e['file'])}  →  {e['table']}  "
          f"[{', '.join(e['ops'])}]")

    # ── Enums ─────────────────────────────────────────────────────
    w("\n" + "─" * 70)
    w("ENUM CATALOGUE")
    w("─" * 70)
    for name, vals in doc["enum_catalogue"]["enums"].items():
        w(f"  {name}: {', '.join(str(v) for v in vals)}")

    w("\n" + "=" * 70)
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────

def _rel(path: str) -> str:
    idx = path.replace("\\", "/").find("src/")
    if idx != -1:
        return path[idx:].replace("\\", "/")
    return path.replace("\\", "/").split("/")[-1]


def _build_table_profiles(known_tables, table_ops, filtered_columns, db_descriptions):
    profiles = {}
    for table in known_tables:
        info = table_ops.get(table, {})
        profiles[table] = {
            "operations":        info.get("operations", []),
            "realtime":          info.get("realtime", False),
            "readers":           info.get("readers", []),
            "writers":           info.get("writers", []),
            "filtered_columns":  filtered_columns.get(table, []),
            "schema_description": db_descriptions.get(table, ""),
        }
    return profiles