"""
output/formatter.py

Produces a Claude-optimized context document that combines:
  • The frontend↔DB relationship graph
  • The pre-generated DB table descriptions
  • A targeted bug report for the Recipes page issue
  • Clear instructions for Claude on how to use this document

The output is a structured JSON file.  A companion plain-text
summary (.txt) is also written for quick human review.
"""

import json
from pathlib import Path
from datetime import datetime


# ── Prose primer Claude reads first ──────────────────────────────────────────
CLAUDE_SYSTEM_PRIMER = (
    "You are a full-stack debugging assistant with expert knowledge of "
    "React/Vite frontends, Supabase (PostgreSQL + PostgREST), and the "
    "Rooialty restaurant management application.\n\n"
    "The document you are about to read was auto-generated by an RAG "
    "pipeline that:\n"
    "  1. Scanned every .js/.jsx file in src/ for Supabase query calls\n"
    "  2. Mapped those calls to known PostgreSQL tables\n"
    "  3. Ran gap-analysis to find tables referenced in the DB but never "
    "     queried in the frontend (and vice-versa)\n"
    "  4. Performed a targeted deep-dive on the Recipes page bug\n\n"
    "Use this context to:\n"
    "  • Trace the exact data-flow path for any feature\n"
    "  • Identify missing queries, broken joins, or wrong filter columns\n"
    "  • Suggest minimal, targeted code fixes\n"
    "  • Answer questions about how the frontend and database are connected"
)


def format_for_claude(
    graph: dict,
    db_output: dict,
    schema: dict,
    scan_result: dict,
) -> dict:
    """
    Assemble the full Claude context document as a Python dict
    (caller serialises to JSON).
    """
    now = datetime.utcnow().isoformat(timespec="seconds") + "Z"

    return {
        "_meta": {
            "generated_at": now,
            "pipeline":     "rooialty_ai_rag",
            "purpose":      "Frontend ↔ DB relationship map + Recipes bug analysis",
        },

        # ── 1. Instructions for Claude ────────────────────────────────────
        "claude_instructions": CLAUDE_SYSTEM_PRIMER,

        # ── 2. High-level stats ───────────────────────────────────────────
        "scan_summary": {
            "total_files_scanned":    scan_result.get("total_scanned", 0),
            "files_using_supabase":   scan_result.get("total_supabase", 0),
            "db_tables_known":        graph["stats"]["total_known_tables"],
            "db_tables_referenced":   graph["stats"]["total_tables_referenced"],
        },

        # ── 3. THE PRIMARY BUG – Recipes page ────────────────────────────
        "primary_bug": {
            "symptom": (
                "On the Recipes page (OfficeRecipes.jsx) the UI shows "
                "'Select an item to configure its recipe'. When a menu item "
                "is selected, NO ingredients appear below it. The user expects "
                "to see ingredients they can add to that item's recipe."
            ),
            "relevant_tables": {
                "items": (
                    "Stores menu items (id, name, category, price, …). "
                    "The item the user selects comes from this table."
                ),
                "ingredients": (
                    "Stores all purchasable/stockable ingredients "
                    "(id, name, unit, cost_per_unit, …). "
                    "These are the things the user should be able to "
                    "ADD to an item's recipe."
                ),
                "item_ingredients": (
                    "JOIN table linking items ↔ ingredients "
                    "(item_id FK → items.id, ingredient_id FK → ingredients.id, "
                    "quantity, unit). "
                    "A row here = 'item X requires Y grams of ingredient Z'. "
                    "THIS TABLE IS THE RECIPE."
                ),
            },
            "analysis":         graph["recipes_analysis"],
        },

        # ── 4. Full frontend → DB edge map ───────────────────────────────
        "frontend_to_db_map": graph["file_to_tables"],

        # ── 5. DB table → frontend coverage ─────────────────────────────
        "db_to_frontend_map": graph["table_to_files"],

        # ── 6. Gap analysis ──────────────────────────────────────────────
        "gap_analysis": {
            "orphan_db_tables": {
                "description": (
                    "These DB tables exist but are NEVER queried from the frontend. "
                    "They may be backend-only, or they may represent missing features."
                ),
                "tables": graph["orphan_tables"],
            },
            "orphan_frontend_files": {
                "description": (
                    "These files use Supabase but reference NO known DB table. "
                    "They may be using dynamic table names or have typos."
                ),
                "files": graph["orphan_files"],
            },
        },

        # ── 7. DB table descriptions (from rooialty_ai/output/) ──────────
        "db_table_descriptions": _summarise_db_output(db_output),

        # ── 8. Schema artefacts ──────────────────────────────────────────
        "schema_artefacts": {
            k: v for k, v in schema.items()
            if k in ("table+column", "constraints", "enums")
        },

        # ── 9. All Supabase-active files (compact) ───────────────────────
        "all_supabase_files": [
            {
                "file":       e["file"],
                "role":       e.get("role"),
                "tables":     e.get("tables", []),
                "operations": e.get("operations", []),
                "realtime":   e.get("realtime", False),
            }
            for e in scan_result.get("supabase_files", [])
        ],
    }


def _summarise_db_output(db_output: dict) -> dict:
    """
    Trim each table description to a sensible length so the context
    document doesn't balloon.  Full text kept for recipe-critical tables.
    """
    KEEP_FULL = {"item_ingredients", "ingredients", "items", "all_tables"}
    MAX_CHARS = 800

    summaries = {}
    for table, text in db_output.items():
        if table in KEEP_FULL or len(text) <= MAX_CHARS:
            summaries[table] = text
        else:
            summaries[table] = text[:MAX_CHARS] + "\n… [truncated – see rooialty_ai/output/]"
    return summaries


def write_outputs(context: dict, output_dir: Path) -> tuple[Path, Path]:
    """
    Write the context to both JSON and a human-readable summary TXT.
    Returns (json_path, txt_path).
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    json_path = output_dir / "claude_context.json"
    txt_path  = output_dir / "claude_context_summary.txt"

    # ── JSON (full machine-readable context) ─────────────────────────────────
    json_path.write_text(
        json.dumps(context, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    # ── Plain-text summary ────────────────────────────────────────────────────
    bug     = context["primary_bug"]
    analysis= bug["analysis"]
    gap     = context["gap_analysis"]

    lines = [
        "=" * 72,
        "ROOIALTY RAG PIPELINE — CLAUDE CONTEXT SUMMARY",
        f"Generated: {context['_meta']['generated_at']}",
        "=" * 72,
        "",
        "── SCAN STATS ──────────────────────────────────────────────────────",
        f"  Files scanned  : {context['scan_summary']['total_files_scanned']}",
        f"  Use Supabase   : {context['scan_summary']['files_using_supabase']}",
        f"  DB tables known: {context['scan_summary']['db_tables_known']}",
        f"  Tables touched : {context['scan_summary']['db_tables_referenced']}",
        "",
        "── PRIMARY BUG: RECIPES PAGE ───────────────────────────────────────",
        f"  Symptom: {bug['symptom']}",
        "",
        f"  Gap detected   : {analysis['gap_detected']}",
        f"  Gap description: {analysis['gap_description']}",
        "",
        "  Recommended fix:",
        *[f"    {line}" for line in analysis["recommended_fix"].splitlines()],
        "",
        "── RECIPES TABLE COVERAGE ──────────────────────────────────────────",
    ]

    for table, files in analysis["table_coverage"].items():
        status = "✅" if files else "❌ NOT QUERIED"
        lines.append(f"  {table:30s} {status}")
        for f in files:
            lines.append(f"    → {f}")

    lines += [
        "",
        "── ORPHAN DB TABLES (never queried from frontend) ──────────────────",
    ]
    for t in gap["orphan_db_tables"]["tables"]:
        lines.append(f"  • {t}")

    lines += [
        "",
        "── ORPHAN FRONTEND FILES (Supabase with no known table) ────────────",
    ]
    for f in gap["orphan_frontend_files"]["files"]:
        lines.append(f"  • {f}")

    lines += ["", "Full detail → claude_context.json", ""]

    txt_path.write_text("\n".join(lines), encoding="utf-8")

    return json_path, txt_path